# Makefile for the focaltech touchscreen drivers.

ifneq ($(KERNELRELEASE),)
    obj-m += focaltech_touch.o
focaltech_touch-y := \
    focaltech_core.o \
    focaltech_ex_fun.o \
    focaltech_ex_mode.o \
    focaltech_gesture.o \
    focaltech_esdcheck.o \
    focaltech_point_report_check.o \
    focaltech_test/focaltech_test.o \
    focaltech_test/focaltech_test_ini.o \
    focaltech_test/supported_ic/focaltech_test_ft5662.o \
    focaltech_flash.o \
    focaltech_spi.o
else
    KDIR = $(OUT)/obj/KERNEL_OBJ
    CROSS_COMPILE = $(ANDROID_TOOLCHAIN)/aarch64-linux-android-
    CLANG = $(ANDROID_BUILD_TOP)/prebuilts/clang/host/linux-x86/clang-r370808
    REAL_CC = $(CLANG)/bin/clang
    AR = $(CLANG)/bin/llvm-ar
    LLVM_NM = $(CLANG)/bin/llvm-nm
    LD = $(CLANG)/bin/ld.lld
.PHONY: clean
endif
